name       : python-html2text
version    : 2018.1.9
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/h/html2text/html2text-2018.1.9.tar.gz : 627514fb30e7566b37be6900df26c2c78a030cc9e6211bda604d8181233bcdd4
license    : GPL-3.0-only
component  : programming.python
summary    : Convert HTML to Markdown-formatted text
description: |
    html2text is a Python script that converts a page of HTML into clean, easy-to-read plain ASCII text. Better yet, that ASCII also happens to be valid Markdown (a text-to-HTML format).
builddeps  :
    - python-coverage
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
check      : |
    %python_test
