name       : python-html2text
version    : 2019.9.26
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/h/html2text/html2text-2019.9.26.tar.gz : 6f56057c5c2993b5cc5b347cb099bdf6d095828fef1b53ef4e2a2bf2a1be9b4f
license    : GPL-3.0-only
component  : programming.python
summary    : Convert HTML to Markdown-formatted text
description: |
    html2text is a Python script that converts a page of HTML into clean, easy-to-read plain ASCII text. Better yet, that ASCII also happens to be valid Markdown (a text-to-HTML format).
build      : |
    %python3_setup
install    : |
    %python3_install
