name       : python-html2text
version    : 2020.1.16
release    : 6
source     :
    - https://pypi.io/packages/source/h/html2text/html2text-2020.1.16.tar.gz : e296318e16b059ddb97f7a8a1d6a5c1d7af4544049a01e261731d2d5cc277bbb
license    : GPL-3.0-only
component  : programming.python
summary    : Convert HTML to Markdown-formatted text
description: |
    html2text is a Python script that converts a page of HTML into clean, easy-to-read plain ASCII text. Better yet, that ASCII also happens to be valid Markdown (a text-to-HTML format).
build      : |
    %python3_setup
install    : |
    %python3_install
